### ISSUE TITLE
URI::InvalidComponentError: bad component(expected host component): http://3b49977a.ngrok.io

### ISSUE THREAD

**Issue by trkrameshkumar** [matiaskorhonen/monit#10]
Hi @matiaskorhonen ,

When i try to run the following line i was getting the error

`status = Monit::Status.new({ :host => "http://3b49977a.ngrok.io",:auth => true, :username => "username",:password => "password" })`

`status.get`

`URI::InvalidComponentError: bad component(expected host component): http://3b49977a.ngrok.io`

**Comment by matiaskorhonen** [comment]
I believe this is because of the `http://` in the host option. The host should be just the host (with no scheme).
